./TP-Delibird_Game-Boy BROKER NEW_POKEMON Vaporeon 5 5 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Jolteon 8 7 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Jolteon 10 7 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Pikachu 9 9 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Pikachu 16 16 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Squirtle 20 20 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Flareon 1 1 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Bulbasaur 3 16 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Onix 10 1 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Espeon 10 9 1
